name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Retag as latest
        run: |
          docker pull mos4ic/mosaic-subnet:alpha
          docker tag mos4ic/mosaic-subnet:alpha mos4ic/mosaic-subnet:latest
          docker push mos4ic/mosaic-subnet:latest
