name: Test

on:
  pull_request:
  push:
    paths:
      - '**.py'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: poetry
          cache-dependency-path: poetry.lock
      - name: Install dependencies
        run: |
          poetry install --no-interaction
      - name: Run tests
        run: poetry run python -m unittest discover -s tests/ -p '*.py'
#      - name: Lint
#        run: pylint $(git ls-files '*.py')
